/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisciplinesRouteImport } from './routes/disciplines'
import { Route as DisciplinesIdRouteImport } from './routes/disciplines.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplinesRoute = DisciplinesRouteImport.update({
  id: '/disciplines',
  path: '/disciplines',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplinesIdRoute = DisciplinesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DisciplinesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disciplines': typeof DisciplinesRouteWithChildren
  '/disciplines/$id': typeof DisciplinesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disciplines': typeof DisciplinesRouteWithChildren
  '/disciplines/$id': typeof DisciplinesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/disciplines': typeof DisciplinesRouteWithChildren
  '/disciplines/$id': typeof DisciplinesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/disciplines' | '/disciplines/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/disciplines' | '/disciplines/$id'
  id: '__root__' | '/' | '/disciplines' | '/disciplines/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisciplinesRoute: typeof DisciplinesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disciplines': {
      id: '/disciplines'
      path: '/disciplines'
      fullPath: '/disciplines'
      preLoaderRoute: typeof DisciplinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disciplines/$id': {
      id: '/disciplines/$id'
      path: '/$id'
      fullPath: '/disciplines/$id'
      preLoaderRoute: typeof DisciplinesIdRouteImport
      parentRoute: typeof DisciplinesRoute
    }
  }
}

interface DisciplinesRouteChildren {
  DisciplinesIdRoute: typeof DisciplinesIdRoute
}

const DisciplinesRouteChildren: DisciplinesRouteChildren = {
  DisciplinesIdRoute: DisciplinesIdRoute,
}

const DisciplinesRouteWithChildren = DisciplinesRoute._addFileChildren(
  DisciplinesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisciplinesRoute: DisciplinesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
