/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DisciplinesRouteImport } from './routes/disciplines'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as MetricasRouteImport } from './routes/metricas'
import { Route as PodcastsRouteImport } from './routes/podcasts'
import { Route as PublicacoesRouteImport } from './routes/publicacoes'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimuladosRouteImport } from './routes/simulados'
import { Route as CommunityIndexRouteImport } from './routes/community/index'
import { Route as CommunityChatRouteImport } from './routes/community/chat'
import { Route as DisciplinesIndexRouteImport } from './routes/disciplines.index'
import { Route as DisciplinesIdRouteImport } from './routes/disciplines.$id'
import { Route as MaterialsIndexRouteImport } from './routes/materials.index'
import { Route as MaterialsIdRouteImport } from './routes/materials/$id'
import { Route as DisciplinesIdPodcastRouteImport } from './routes/disciplines/$id/podcast'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplinesRoute = DisciplinesRouteImport.update({
  id: '/disciplines',
  path: '/disciplines',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricasRoute = MetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsRoute = PodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicacoesRoute = PublicacoesRouteImport.update({
  id: '/publicacoes',
  path: '/publicacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladosRoute = SimuladosRouteImport.update({
  id: '/simulados',
  path: '/simulados',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityChatRoute = CommunityChatRouteImport.update({
  id: '/community/chat',
  path: '/community/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplinesIndexRoute = DisciplinesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DisciplinesRoute,
} as any)
const DisciplinesIdRoute = DisciplinesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DisciplinesRoute,
} as any)
const MaterialsIndexRoute = MaterialsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MaterialsRoute,
} as any)
const MaterialsIdRoute = MaterialsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MaterialsRoute,
} as any)
const DisciplinesIdPodcastRoute = DisciplinesIdPodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => DisciplinesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/calendar': typeof CalendarRoute
  '/disciplines': typeof DisciplinesRouteWithChildren
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRouteWithChildren
  '/metricas': typeof MetricasRoute
  '/podcasts': typeof PodcastsRoute
  '/publicacoes': typeof PublicacoesRoute
  '/ranking': typeof RankingRoute
  '/settings': typeof SettingsRoute
  '/simulados': typeof SimuladosRoute
  '/community/chat': typeof CommunityChatRoute
  '/disciplines/$id': typeof DisciplinesIdRouteWithChildren
  '/materials/$id': typeof MaterialsIdRoute
  '/community/': typeof CommunityIndexRoute
  '/disciplines/': typeof DisciplinesIndexRoute
  '/materials/': typeof MaterialsIndexRoute
  '/disciplines/$id/podcast': typeof DisciplinesIdPodcastRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/metricas': typeof MetricasRoute
  '/podcasts': typeof PodcastsRoute
  '/publicacoes': typeof PublicacoesRoute
  '/ranking': typeof RankingRoute
  '/settings': typeof SettingsRoute
  '/simulados': typeof SimuladosRoute
  '/community/chat': typeof CommunityChatRoute
  '/disciplines/$id': typeof DisciplinesIdRouteWithChildren
  '/materials/$id': typeof MaterialsIdRoute
  '/community': typeof CommunityIndexRoute
  '/disciplines': typeof DisciplinesIndexRoute
  '/materials': typeof MaterialsIndexRoute
  '/disciplines/$id/podcast': typeof DisciplinesIdPodcastRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/calendar': typeof CalendarRoute
  '/disciplines': typeof DisciplinesRouteWithChildren
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRouteWithChildren
  '/metricas': typeof MetricasRoute
  '/podcasts': typeof PodcastsRoute
  '/publicacoes': typeof PublicacoesRoute
  '/ranking': typeof RankingRoute
  '/settings': typeof SettingsRoute
  '/simulados': typeof SimuladosRoute
  '/community/chat': typeof CommunityChatRoute
  '/disciplines/$id': typeof DisciplinesIdRouteWithChildren
  '/materials/$id': typeof MaterialsIdRoute
  '/community/': typeof CommunityIndexRoute
  '/disciplines/': typeof DisciplinesIndexRoute
  '/materials/': typeof MaterialsIndexRoute
  '/disciplines/$id/podcast': typeof DisciplinesIdPodcastRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculadora'
    | '/calendar'
    | '/disciplines'
    | '/login'
    | '/materials'
    | '/metricas'
    | '/podcasts'
    | '/publicacoes'
    | '/ranking'
    | '/settings'
    | '/simulados'
    | '/community/chat'
    | '/disciplines/$id'
    | '/materials/$id'
    | '/community/'
    | '/disciplines/'
    | '/materials/'
    | '/disciplines/$id/podcast'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculadora'
    | '/calendar'
    | '/login'
    | '/metricas'
    | '/podcasts'
    | '/publicacoes'
    | '/ranking'
    | '/settings'
    | '/simulados'
    | '/community/chat'
    | '/disciplines/$id'
    | '/materials/$id'
    | '/community'
    | '/disciplines'
    | '/materials'
    | '/disciplines/$id/podcast'
  id:
    | '__root__'
    | '/'
    | '/calculadora'
    | '/calendar'
    | '/disciplines'
    | '/login'
    | '/materials'
    | '/metricas'
    | '/podcasts'
    | '/publicacoes'
    | '/ranking'
    | '/settings'
    | '/simulados'
    | '/community/chat'
    | '/disciplines/$id'
    | '/materials/$id'
    | '/community/'
    | '/disciplines/'
    | '/materials/'
    | '/disciplines/$id/podcast'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculadoraRoute: typeof CalculadoraRoute
  CalendarRoute: typeof CalendarRoute
  DisciplinesRoute: typeof DisciplinesRouteWithChildren
  LoginRoute: typeof LoginRoute
  MaterialsRoute: typeof MaterialsRouteWithChildren
  MetricasRoute: typeof MetricasRoute
  PodcastsRoute: typeof PodcastsRoute
  PublicacoesRoute: typeof PublicacoesRoute
  RankingRoute: typeof RankingRoute
  SettingsRoute: typeof SettingsRoute
  SimuladosRoute: typeof SimuladosRoute
  CommunityChatRoute: typeof CommunityChatRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disciplines': {
      id: '/disciplines'
      path: '/disciplines'
      fullPath: '/disciplines'
      preLoaderRoute: typeof DisciplinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metricas': {
      id: '/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof MetricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts': {
      id: '/podcasts'
      path: '/podcasts'
      fullPath: '/podcasts'
      preLoaderRoute: typeof PodcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicacoes': {
      id: '/publicacoes'
      path: '/publicacoes'
      fullPath: '/publicacoes'
      preLoaderRoute: typeof PublicacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulados': {
      id: '/simulados'
      path: '/simulados'
      fullPath: '/simulados'
      preLoaderRoute: typeof SimuladosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/chat': {
      id: '/community/chat'
      path: '/community/chat'
      fullPath: '/community/chat'
      preLoaderRoute: typeof CommunityChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disciplines/': {
      id: '/disciplines/'
      path: '/'
      fullPath: '/disciplines/'
      preLoaderRoute: typeof DisciplinesIndexRouteImport
      parentRoute: typeof DisciplinesRoute
    }
    '/disciplines/$id': {
      id: '/disciplines/$id'
      path: '/$id'
      fullPath: '/disciplines/$id'
      preLoaderRoute: typeof DisciplinesIdRouteImport
      parentRoute: typeof DisciplinesRoute
    }
    '/materials/': {
      id: '/materials/'
      path: '/'
      fullPath: '/materials/'
      preLoaderRoute: typeof MaterialsIndexRouteImport
      parentRoute: typeof MaterialsRoute
    }
    '/materials/$id': {
      id: '/materials/$id'
      path: '/$id'
      fullPath: '/materials/$id'
      preLoaderRoute: typeof MaterialsIdRouteImport
      parentRoute: typeof MaterialsRoute
    }
    '/disciplines/$id/podcast': {
      id: '/disciplines/$id/podcast'
      path: '/podcast'
      fullPath: '/disciplines/$id/podcast'
      preLoaderRoute: typeof DisciplinesIdPodcastRouteImport
      parentRoute: typeof DisciplinesIdRoute
    }
  }
}

interface DisciplinesIdRouteChildren {
  DisciplinesIdPodcastRoute: typeof DisciplinesIdPodcastRoute
}

const DisciplinesIdRouteChildren: DisciplinesIdRouteChildren = {
  DisciplinesIdPodcastRoute: DisciplinesIdPodcastRoute,
}

const DisciplinesIdRouteWithChildren = DisciplinesIdRoute._addFileChildren(
  DisciplinesIdRouteChildren,
)

interface DisciplinesRouteChildren {
  DisciplinesIdRoute: typeof DisciplinesIdRouteWithChildren
  DisciplinesIndexRoute: typeof DisciplinesIndexRoute
}

const DisciplinesRouteChildren: DisciplinesRouteChildren = {
  DisciplinesIdRoute: DisciplinesIdRouteWithChildren,
  DisciplinesIndexRoute: DisciplinesIndexRoute,
}

const DisciplinesRouteWithChildren = DisciplinesRoute._addFileChildren(
  DisciplinesRouteChildren,
)

interface MaterialsRouteChildren {
  MaterialsIdRoute: typeof MaterialsIdRoute
  MaterialsIndexRoute: typeof MaterialsIndexRoute
}

const MaterialsRouteChildren: MaterialsRouteChildren = {
  MaterialsIdRoute: MaterialsIdRoute,
  MaterialsIndexRoute: MaterialsIndexRoute,
}

const MaterialsRouteWithChildren = MaterialsRoute._addFileChildren(
  MaterialsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculadoraRoute: CalculadoraRoute,
  CalendarRoute: CalendarRoute,
  DisciplinesRoute: DisciplinesRouteWithChildren,
  LoginRoute: LoginRoute,
  MaterialsRoute: MaterialsRouteWithChildren,
  MetricasRoute: MetricasRoute,
  PodcastsRoute: PodcastsRoute,
  PublicacoesRoute: PublicacoesRoute,
  RankingRoute: RankingRoute,
  SettingsRoute: SettingsRoute,
  SimuladosRoute: SimuladosRoute,
  CommunityChatRoute: CommunityChatRoute,
  CommunityIndexRoute: CommunityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
